//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using LifeIdea.LazyCure.Interfaces;

namespace LifeIdea.LazyCure.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    public sealed partial class Settings : ApplicationSettingsBase,ISettings {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("TimeLogs")]
        public string TimeLogsFolder {
            get {
                return ((string)(this["TimeLogsFolder"]));
            }
            set {
                this["TimeLogsFolder"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SaveAfterDone {
            get {
                return ((bool)(this["SaveAfterDone"]));
            }
            set {
                this["SaveAfterDone"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int MaxActivitiesInHistory {
            get {
                return ((int)(this["MaxActivitiesInHistory"]));
            }
            set {
                this["MaxActivitiesInHistory"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("01:00:00")]
        public TimeSpan ReminderTime {
            get {
                return ((TimeSpan)(this["ReminderTime"]));
            }
            set {
                this["ReminderTime"] = value;
            }
        }
    }
}
