//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeIdea.LazyCure.Shared.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeIdea.LazyCure.Shared.Constants.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fix the error and start LazyCure again. Sorry for inconveniences..
        /// </summary>
        public static string AskToFixAndExcuse {
            get {
                return ResourceManager.GetString("AskToFixAndExcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be redefined.
        /// </summary>
        public static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Log could not be saved. Exit from LazyCure anyway?.
        /// </summary>
        public static string CouldNotSaveTimeLogDuringExitMessage {
            get {
                return ResourceManager.GetString("CouldNotSaveTimeLogDuringExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current activity is lasting.
        /// </summary>
        public static string CurrentActivityIsLasting {
            get {
                return ResourceManager.GetString("CurrentActivityIsLasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (specify what you are doing).
        /// </summary>
        public static string DefaultActivity {
            get {
                return ResourceManager.GetString("DefaultActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string DefaultLocale {
            get {
                return ResourceManager.GetString("DefaultLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected task &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteTaskConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteTaskConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lazycure.com/donate-to-lazycure.
        /// </summary>
        public static string DonateLink {
            get {
                return ResourceManager.GetString("DonateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log current activity before LazyCure will be closed?.
        /// </summary>
        public static string DoYouWantToLogCurrentActivityBeforeClosure {
            get {
                return ResourceManager.GetString("DoYouWantToLogCurrentActivityBeforeClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} for {1}.
        /// </summary>
        public static string FromAndFor {
            get {
                return ResourceManager.GetString("FromAndFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activity.
        /// </summary>
        public static string GeneratedActivity {
            get {
                return ResourceManager.GetString("GeneratedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LazyCure.html.
        /// </summary>
        public static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file was not found. Please, check that original files from LazyCure installation are present..
        /// </summary>
        public static string HelpFileWasNotFound {
            get {
                return ResourceManager.GetString("HelpFileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect settings.
        /// </summary>
        public static string IncorrectSettings {
            get {
                return ResourceManager.GetString("IncorrectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value in &apos;{0}&apos; column is not correct.
        /// </summary>
        public static string IncorrectValueInColumn {
            get {
                return ResourceManager.GetString("IncorrectValueInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid reminder time. Please, correct it and press &apos;OK&apos; then.
        /// </summary>
        public static string InvalidReminderTime {
            get {
                return ResourceManager.GetString("InvalidReminderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time value.
        /// </summary>
        public static string InvalidTimeValue {
            get {
                return ResourceManager.GetString("InvalidTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time value was specified. Please, specify valid time from 0:00 to 23:59..
        /// </summary>
        public static string InvalidTimeWarning {
            get {
                return ResourceManager.GetString("InvalidTimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        public static string LanguageChange {
            get {
                return ResourceManager.GetString("LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LazyCure error.
        /// </summary>
        public static string LazyCureError {
            get {
                return ResourceManager.GetString("LazyCureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LazyCure is shutting down.
        /// </summary>
        public static string LazyCureIsShuttingDown {
            get {
                return ResourceManager.GetString("LazyCureIsShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task....
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter not empty activity name..
        /// </summary>
        public static string PleaseEnterNotEmptyActivityName {
            get {
                return ResourceManager.GetString("PleaseEnterNotEmptyActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        public static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving error.
        /// </summary>
        public static string SavingError {
            get {
                return ResourceManager.GetString("SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading application settings.
        /// </summary>
        public static string SettingsReadError {
            get {
                return ResourceManager.GetString("SettingsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLog could not be loaded.
        /// </summary>
        public static string TimeLogCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("TimeLogCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLog error.
        /// </summary>
        public static string TimeLogError {
            get {
                return ResourceManager.GetString("TimeLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time log has not been saved.
        /// </summary>
        public static string TimeLogHasNotBeenSaved {
            get {
                return ResourceManager.GetString("TimeLogHasNotBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweeting.
        /// </summary>
        public static string Tweeting {
            get {
                return ResourceManager.GetString("Tweeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
